services:
  db:
    image: ${PGDB_IMAGE_NAME}
    container_name: ${PGDB_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - tegachan-network

  app:
    image: ${APP_IMAGE_NAME}
    container_name: ${APP_CONTAINER_NAME}
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - tegachan-network
    depends_on:
      - db

volumes:
  pgdata:

networks:
  tegachan-network:
    driver: bridge