name: Build and test pipeline

on: push

env:
  MONGODB_URI: ${{ secrets.MONGODB_URI }}
  MONGODB_NAME: ${{ secrets.MONGODB_NAME }}
  MONGODB_URI_DEV: ${{ secrets.MONGODB_URI_DEV }}
  MONGODB_NAME_DEV: ${{ secrets.MONGODB_NAME_DEV }}
  MONGODB_URI_TEST: ${{ secrets.MONGODB_URI_TEST }}
  MONGODB_NAME_TEST: ${{ secrets.MONGODB_NAME_TEST }}
  AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME}}
  AWS_BUCKET_URL: ${{ secrets.AWS_BUCKET_URL }}
  AWS_BUCKET_NAME_DEV: ${{ secrets.AWS_BUCKET_NAME_DEV }}
  AWS_BUCKET_URL_DEV: ${{ secrets.AWS_BUCKET_URL_DEV }}
  AWS_BUCKET_NAME_TEST: ${{ secrets.AWS_BUCKET_NAME_TEST }}
  AWS_BUCKET_URL_TEST: ${{ secrets.AWS_BUCKET_URL_TEST }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Build
        run: npm run build --if-present
      - name: Run unit and integration tests
        run: npm test
      - name: Run e2e tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          browser: chrome
          headed: true
          wait-on: http://localhost:3000